### ISSUE TITLE
Heroku Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (970485)

### ISSUE THREAD

**Issue by Rohith-sreedharan** [jontewks/puppeteer-heroku-buildpack#101]
Actually am making an API for some works with puppeteer, it works in my local bcoz i had executable path

also in docs it says no need for set executable path but my error is
```
Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (970485).
```
My code For the launch() is
```
const browser = await puppeteer.launch({
            args: [
                '--no-sandbox'
            ],
        });
        const page = await browser.newPage();
```
Here i use Heroku and this build pack and yet i get this error

lmk where i made the error thank you

**Comment by jontewks** [comment]
Hey @Rohith-sreedharan, are you able to post more of that particular repo, including package.json? This buildpack only installs the libraries necessary to allow chromium to run, but doesn't effect how puppeteer works at all, so that error is something to do with puppeteer. I'll still see if I can help out though!

**Comment by Rohith-sreedharan** [comment]
yea sure so i am sending my package.json for more info

**Comment by Rohith-sreedharan** [comment]
my whole package.json files

```
{
  "name": "api",
  "version": "1.0.0",
  "description": "An Api for Newsletters",
  "main": "main.js",
  "scripts": {
    "test": "test.js",
    "start": "node main.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Rohith-sreedharan/api-newsletter.git"
  },
  "keywords": [
    "API"
  ],
  "author": "Rohithaditya",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Rohith-sreedharan/api-newsletter/issues"
  },
  "homepage": "https://github.com/Rohith-sreedharan/api-newsletter#readme",
  "dependencies": {
      "express": "4.17.3",
      "puppeteer-core": "13.5.2"
    }
  }
```

**Comment by jontewks** [comment]
Install puppeteer not puppeteer-core. Puppeteer-core is specifically made for not downloading a browser along with it.

> puppeteer-core
Since version 1.7.0 we publish the [puppeteer-core](https://www.npmjs.com/package/puppeteer-core) package, a version of Puppeteer that doesn't download any browser by default.

npm i puppeteer-core
# or "yarn add puppeteer-core"
puppeteer-core is intended to be a lightweight version of Puppeteer for launching an existing browser installation or for connecting to a remote one. Be sure that the version of puppeteer-core you install is compatible with the browser you intend to connect to.

See [puppeteer vs puppeteer-core](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core).

**Comment by Rohith-sreedharan** [comment]
oh ok thanks for letting me know, is there an build pack for it to?

**Comment by jontewks** [comment]
@Rohith-sreedharan this is the buildpack that you'll need to get chromium running on Heroku.
