### ISSUE TITLE
adding Chinese font support

### ISSUE THREAD

**Issue by jonknapp** [jontewks/puppeteer-heroku-buildpack#2]
As a heads up, I forked this buildpack and made one that adds Chinese, Japanese, and Korean font support: https://github.com/CoffeeAndCode/puppeteer-heroku-buildpack

It was created by following the work done in https://github.com/dscout/wkhtmltopdf-buildpack/pull/14/files

If you think this is something you'd like added to your buildpack I can create a PR for it. Otherwise, feel free to close this one out. Thanks for putting this out there!

**Comment by jontewks** [comment]
Hello fellow Jon

Thanks for doing that. I'm not sure about the demand for these at the moment and have already had someone ask about caching the installs since there are quite a few dependencies, so I am a bit weary of adding the additional 22mb of installs if the fonts won't be used in the majority case.

Since you already have it on your fork though, I think it would be best to give people both options. I'll mention your fork in the readme and point people there if they want the additional font support, but can use this one if they don't need it to save a small amount of time or if the final slug size is important.

Thanks again!

**Comment by jonknapp** [comment]
👍 rock on!
