### ISSUE TITLE
Issue when upgrading to stack heroku-18

### ISSUE THREAD

**Issue by diervo** [jontewks/puppeteer-heroku-buildpack#27]
I just run into an issue after deploying the exact same project (same npm dependencies and puppeteer) in the new heroku stack `heroku-18`

```
/app/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libxcb-shm.so.0: cannot open shared object file: No such file or directory
```

Nothing else has changed, so I believe must be due to the new image upgrade?
I'm using 1.7 version of pupeteer

**Comment by jontewks** [comment]
Hey @diervo thanks a lot for letting me know.

Can you please try resetting your build cache? The instructions for that are here: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Then just make another commit to your project and push it to heroku which will cause heroku to run the build step again (just restarting dynos won't do this).

If that doesn't resolve it please let me know and we will figure it out!

**Comment by diervo** [comment]
@jontewks Thanks for the quick response.

I did two things removed the cache and used the buildpacks:
heroku/nodejs
https://buildpack-registry.s3.amazonaws.com/buildpacks/jontewks/puppeteer.tgz

I got a similar error:

```
/app/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libpangoft2-1.0.so.0: cannot open shared object file: No such file or directory
```

And also I started brand new app (private spaces)
with the master webpack: (https://github.com/jontewks/puppeteer-heroku-buildpack)
And with that I got the issue I stated previously.

**Comment by jontewks** [comment]
@diervo thats odd since that library is listed in the buildpack.

Ok a few more things to try, can you try swapping the order of the buildpacks on heroku? This has seemed to help people in the past.

Can you also post your package.json just so we can peek at the version requirement for puppeteer? 

Also would you mind posting how you are calling puppeteer in your code? Specifically where you call `puppeteer.launch`?

**Comment by diervo** [comment]
@jontewks Very odd, I just install it again from scratch, and ever time I get a different runtime missing dependency:

```
Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libpangoft2-1.0.so.0: cannot open shared object file: No such file or directory
```

Here is the full logs and the way I use puppeteer:
https://gist.github.com/diervo/921f04eef06c824bb9c43578e6c88729

For the record I have like 10 other instances up and running, it just started failing now...

**Comment by diervo** [comment]
Isn't: `libxcb-shm` missing?

**Comment by jontewks** [comment]
Might be worth trying the forced garbage collection part of this as well?  http://engineering.generalassemb.ly/post/143896522629/the-heroku-build-cache-and-exceeding-compiled-slug

**Comment by diervo** [comment]
@jontewks I send you a PR request. A library was missing.

**Comment by jontewks** [comment]
Yes but my concern is that heroku lists that package as available on heroku-18 all the time, and that I am not running into that issue myself with the test app. It would be pretty concerning to need to install dependencies even when heroku says they are available to your applications. Hoping to get to the bottom of the issue you are running into rather than patching it

**Comment by jontewks** [comment]
@diervo I see you have your buildpack up so at least you aren't stuck, my concern is that once it showed one lib missing that should have been there, and another time it showed a lib missing that was specifically installed by this buildpack, so it really seems like there is something else going on that I'm not aware of since adding the dependency to the buildpack list didn't fix the issue in one of those cases.

If your code is public someplace I'd love to try to deploy it to an app as well and see what happens. Did you try different orders of buildpacks? Can you post a screenshot of your current setup? Also could you confirm the puppeteer version from your package.json?

**Comment by diervo** [comment]
@jontewks the other library was because I was using your old buildpack. You haven't upgraded `heroku buildpacks:set jontewks/puppeteer` I think.

**Comment by diervo** [comment]
Sorry the code is not yet public. If you are willing to sign a Salesforce NDA I can give you access :)

**Comment by jontewks** [comment]
>@jontewks the other library was because I was using your old buildpack. You haven't upgraded heroku buildpacks:set jontewks/puppeteer I think.

Thanks, I didn't realize I had to update heroku buildpacks manually, so that should be resolved.

A few last ditch effort things to try since its pretty strange that the issue only seems to be affecting you:

1. Can you try updating puppeteer to the latest version (1.8.0)? Its a different version of chromium, so its worth a shot
1. Can you run the following command and let me know the output: `heroku apps:info -a APP_NAME`
1. Can you run the following commands to open a bash shell on your app and manually inspect whether or not the library in question is available to you:

- `heroku run bash -a APP_NAME`
- Once shell is up and running, `dpkg -s libxcb-shm0`, and paste that output as well?

Connecting to my test app and doing the above I'm getting 
```bash
~ $ dpkg -s libxcb-shm0
Package: libxcb-shm0
Status: install ok installed
```

**Comment by jontewks** [comment]
Haven't heard back in a week, hopefully the issue is resolved for you somehow. I couldn't replicate this on my test apps or my company's production apps. Feel free to open the issue back up if its still happening.
