### ISSUE TITLE
apt-get warning: `W: --force-yes is deprecated, use one of the options starting with --allow instead.`

### ISSUE THREAD

**Issue by josephfrazier** [jontewks/puppeteer-heroku-buildpack#29]
Hey Jon, thanks for making this! I'm just getting started, but I expect it to be super useful for my project.

I noticed in my heroku build log that there's a bunch of `apt-get` warnings like this:

```
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```

It looks like this line is the one responsible: https://github.com/jontewks/puppeteer-heroku-buildpack/blob/22c5b5960775a5befb89e8b9a1014bc8c1187e3f/bin/compile#L56

According to the [`apt-get` man page](https://manpages.debian.org/stretch/apt/apt-get.8.en.html), we can use `--allow-downgrades --allow-remove-essential --allow-change-held-packages` instead. Would you be open to a PR with that change?

**Comment by jontewks** [comment]
Thanks @josephfrazier.

This was actually talked about previously in https://github.com/jontewks/puppeteer-heroku-buildpack/issues/8. I was hoping to stick closely to the heroku buildpacks but it seems like they aren't updated as often as I thought.

I was also holding off on changes since it sounded like the cedar-14 stack wouldn't support some of the flags needed according to this: https://github.com/heroku/heroku-buildpack-google-chrome/pull/49. Reading a bit more into it though it seems like that may not be the case. Also I can't confirm but I really doubt anyone is using Puppeteer on a cedar-14 app.

Feel free to open that PR and I'll test on my test app and see if I'm able to start a new cedar-14 app as well to test with.

**Comment by jontewks** [comment]
Closing the issue but still open to a PR for testing.

**Comment by josephfrazier** [comment]
Thanks, just opened https://github.com/jontewks/puppeteer-heroku-buildpack/pull/30!
