### ISSUE TITLE
Help me make the Puppeteer work on Heroku

### ISSUE THREAD

**Issue by lotuspolarbear** [jontewks/puppeteer-heroku-buildpack#41]
Hi, @jontewks.
Recently I built cron job app using MERN stack and I used Puppeteer to scrap the data from web pages.
It worked properly on my local environment but I found that never worked on Heroku, for chrome browsers were not able to open on Heroku.
I just used Puppeteer like this without installing other required modules.

const browser = await puppeteer.launch({ headless: false });

My OS is Win10 and please let me know how to make Puppeteer work properly on Heroku step by step.
Looking forward to hearing back from you.
Thanks
Polar Bear

**Comment by jontewks** [comment]
Hey @lotuspolarbear, I don't believe you can use puppeteer in headless mode on heroku since there is no place for the GUI to be shown. Have you tried it without `headless: false`?

I can't help with a step by step instruction manual on how to get puppeteer working for you since every use case is different. The examples found in the puppeteer documentation all work as intended by simply including this buildpack on your heroku app. I'd maybe start with one of those and begin introducing changes closer to what you want to have happen until something breaks.

Other than that I'm happy to help with issues relating to this buildpack specifically.
