### ISSUE TITLE
Long running tasks

### ISSUE THREAD

**Issue by lynxionxs** [jontewks/puppeteer-heroku-buildpack#47]
Do i have to declare a worker.js process to run operations that take an hour or more to complete, then run this buildpack from there. Not web dyno ?

**Comment by jontewks** [comment]
The buildpack is added to the app on heroku and doesn't change based on dyno types running there. Depending on your setup and whats running you might want to use a worker type dyno rather than web as web type has a 30 second window when response data must be sent.

If you have further questions about that I'd suggest reaching out to heroku as this buildpack is just for getting pupeteer running on heroku and the question seems to be more about Heroku dyno formations and working within their limits.
