### ISSUE TITLE
Where to define the `--no-sandbox` argument?

### ISSUE THREAD

**Issue by lee-40square** [jontewks/puppeteer-heroku-buildpack#54]
Sorry for the simple question but I'm not clear on these instructions:
```
Be sure to include { args: ['--no-sandbox'] } in your call to puppeteer.launch
```
Where am I supposed to call `puppeteer.launch` from and where am I supposed to add the arguments?

Thanks.

**Comment by jontewks** [comment]
Hey @lee-40square, no worries. 

Here is an example of a basic use case of puppeteer and how you'd call that function: https://github.com/GoogleChrome/puppeteer#usage

Basically in order to use puppeteer for its intended purpose you'd have to call that function to get the ball rolling. Here is the full docs for that function and the arguments it takes: https://github.com/GoogleChrome/puppeteer/blob/v2.0.0/docs/api.md#puppeteerlaunchoptions
