### ISSUE TITLE
PDF discrepancy when using page.emulateMediaType('screen')

### ISSUE THREAD

**Issue by tmswartz12** [jontewks/puppeteer-heroku-buildpack#59]
**I am attempting to create a PDF of my screen using** 
```
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    })
    console.log('browser has been opened')
    const page = await browser.newPage()
    page.setViewport({width: 1000, height: 1056})
    await page.waitFor(1000)
    await page.emulateMediaType('screen')
    await page.waitFor(5000)
    console.log('about to create PDF - standby')
    const pdf = await page.pdf({
      format: 'Letter',
      printBackground: true,
      path: MY PATH
    })
    console.log('pdf created')
    await browser.close()
    console.log('browser closed')
  }
```

### **Locally.. my PDF is returned to my browser with the proper sizing and formatting.. however. when running in production.. my formatting / margins are off..** 

This creates awkward page breaks in the middle of my content and is not suitable for my client!

I am using `"puppeteer": "^2.00.0"`

### Does this buildpack effect `await page.emulateMediaType('screen')`?
- if so.. has anyone been able to fix this issue?

Thanks in advance for your help!!!

**Comment by tmswartz12** [comment]
After further research.. a better question may be to ask... does this buildpack support the recent puppeteer 2.00.0 version?

I am lead to believe my issue is either related to Heroku or this buildpack because my PDF is generated as intended in my local env. 

- [API Release Notes For Reference](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-release-notes)

I am using node version 

``` 
 "engines": {
    "node": "8.16.2"
  }
```

**Comment by jontewks** [comment]
Hey sorry for slow response, have been traveling for the holidays.

All this buildpack does is add some dependencies to the linux environment on heroku so that chromium can run correctly. All it does for puppeteer is allow chromium to start correctly, and shouldn't have any effect on how chromium acts or what it does after that.

This buildpack does still work for puppeteer versions 2 and greater as the main chromium dependencies didn't change. Sorry I can't help with the issue you are experiencing though. I'd guess you would get a much better response asking this question on the puppeteer github page as it sounds like mainly a usage issue and differences that shouldn't exist between headless true and false.

Good luck!
