### ISSUE TITLE
[Heroku] Compiled slug size is too large

### ISSUE THREAD

**Issue by etozzato** [jontewks/puppeteer-heroku-buildpack#69]
The puppeteer buildpack was removed from my instance and I only found out trying to generate a PDF. Now I am trying to redeploy with ruby, node, and puppeteer and the slug is exceeding the limit of 500Mb by 124.7Mb :(

I wonder if there is an alternative to deploy the necessary binaries for puppeteer or reduce the size of the heroku/ruby buildpack! 

Any other information needed? Stack is heroku-18

**Comment by jontewks** [comment]
Hey @etozzato 

One thing that might be worth trying would be this: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

I've also run into size issues on heroku when I really shouldn't have been, and starting a new app and adding the same buildpacks and code lowered the slug size, so that might be a second thing to try if the first doesn't work.

May also try the other command listed here for git cleanup: https://thoughtbot.com/blog/how-to-reduce-a-large-heroku-compiled-slug-size.

If none of those work, you may want to see if it is possible for you to deploy puppeteer in this case with just one language, ruby or node, instead of both.

Hope something here is helpful!

**Comment by kwent** [comment]
Running into the same issue. I'm trying to cleanup as much as i can by excluding other stuff but `x86_64-linux-gnu` is eating all my space. Any idea ? Are all those dependencies required ?

```
/usr/lib $ du -ha --max-depth 1 . | sort -hr
364M	.
222M	./x86_64-linux-gnu
64M	./gcc
26M	./git-core
22M	./python3.8
11M	./ruby
7.2M	./locale
5.6M	./file
2.6M	./postgresql
```

**Comment by jontewks** [comment]
Sometimes I get the feeling that its really hard to actually clear out everything heroku caches as slug sizes can be so widely different and hard to lower. Below is a pic of the test project I use that has node and my buildpack installed and the slug size is just over 300MB. Do you happen to have any other buildpacks in your list too?

![2021-01-28_09-53-53](https://user-images.githubusercontent.com/3970573/106163541-e73fe600-614e-11eb-94ee-9e9fd78858cd.png)

**Comment by kwent** [comment]
Yeah...

![Screen Shot 2021-01-29 at 2 15 57 AM](https://user-images.githubusercontent.com/879780/106262500-f9199b80-61d7-11eb-90ce-06abecef94ea.png)
![Screen Shot 2021-01-29 at 2 16 00 AM](https://user-images.githubusercontent.com/879780/106262504-fae35f00-61d7-11eb-99c7-51d26e2e1363.png)

When i add https://github.com/jontewks/puppeteer-heroku-buildpack everything explodes and slug size is 533Mb.

**Comment by jontewks** [comment]
![2021-01-29_08-49-17](https://user-images.githubusercontent.com/3970573/106289580-09993880-620f-11eb-8343-55dc1cd95bf1.png)

I tried adding those buildpacks as well and have a much lower total. Have you tried setting up a brand new project with all the same buildpacks and code too to see if that changes anything?

I do not know what it would take to download specific chromiums since thats completely handled by puppeteer, this buildpack is only to add the dependencies puppeteer needs to run.

**Comment by kwent** [comment]
Probably cause my Rails project has lot of gems included.

I’ll need to dig into how to download a specific chromium then I’ll give a
shot and keep you posted.

**Comment by jontewks** [comment]
This may be an option: https://github.com/puppeteer/puppeteer/issues/3027#issuecomment-411211912

Previously we've had a decently large app and needed to use puppeteer and so we turned the puppeteer running on heroku into its own microservice to keep it separate from the main app. That made it easier to work on and change, as well as kept the slug size below the limit.
