### ISSUE TITLE
Puppeteer along with puppeteer-heroku-builpack increases heroku slug by 300mb!

### ISSUE THREAD

**Issue by pieroliviermarquis** [jontewks/puppeteer-heroku-buildpack#90]
I have installed prerender-spa-plugin which requires puppeteer. I have followed all the steps included in this repo and the troubleshooting page, cleared the cached, but my slug size has still increased by 300mb. I can't delete enough dependencies to make this work. Is there a solution for this? 

I believe I do not need chromium after my app is deployed, is there a way to delete it at that point. Could I install it without the interactive_ui_tests?

**Comment by jontewks** [comment]
Hey @pieroliviermarquis, Puppeteer is about 300 MB due to the Chromium install. From their docs: 

> Note: When you install Puppeteer, it downloads a recent version of Chromium (~170MB Mac, ~282MB Linux, ~280MB Win) that is guaranteed to work with the API. To skip the download, download into another path, or download a different browser, see Environment variables.

If that is causing size issues with your project the best bet is to pull the Puppeteer specific stuff into its own repo and deploy it as a microservice that your main app can interact with but is deployed separately, thats what we had to do at the last place I worked. 

You said you believe you don't need chromium after the app is deployed, so does that mean you don't use Puppeteer once the app is deployed? If you are using Puppeteer you are going to need Chromium installed, as thats what it uses to actually act as a browser.

Good luck!
